import machine
import socket
from utils.html_generator import HtmlGenerator
from pin_handler import PinHandler
from wifi_ap_module import WifiAPManager

class WebServer:
    def __init__(self, WIFI_SSID, WIFI_PASSWORD, pin_numbers):
        self.WIFI_SSID = WIFI_SSID
        self.WIFI_PASSWORD = WIFI_PASSWORD
        self.pin_numbers = pin_numbers
        self.pins = [machine.Pin(pin, machine.Pin.OUT) for pin in pin_numbers]
        self.htmlGenerator = HtmlGenerator(pin_numbers)
        self.html = self.htmlGenerator.create_html()
        self.pin_handler = PinHandler(self.pins, self.pin_numbers)
        self.wifi_manager = WifiAPManager(WIFI_SSID, WIFI_PASSWORD)

    def start_server(self):
        self.wifi_manager.create_wifi_ap()

        addr = "192.168.4.1"  # The IP address of the network generated by the ESP32
        print("Web server started on", addr)

        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.bind((addr, 80))
        s.listen(5)

        while True:
            conn, addr = s.accept()
            print("Client connected from", addr)

            request = conn.recv(1024)
            request = str(request)

            self.pin_handler.handle_request(request)

            # Send header instead of text
            conn.send("HTTP/1.1 200 OK\nContent-Type: text/html\n\n")

            # Sending the body of the message at once
            conn.sendall(self.html)
            conn.close()
